### ISSUE TITLE
Data Removal Request

### ISSUE THREAD

**Issue by EgorAdonev** [NIRVANA101/Russian-GBSB#2]
I would like to request the removal of the following information:
https://github.com/NIRVANA101/Russian-GBSB/tree/main/CONTENTS/Emails/emails.json

Due to the following reasons:

According to Federal Law No. 152-FZ "On Personal Data".  The law has the following definition of personal data:
 “Personal data is any information relating to a directly or indirectly identified or identifiable natural person”

Emails are also personal data.  In the Ruling of the Supreme Court dated February 26, 2019 in case No. А51-5205/2018, the court found it lawful to hold liable for the disclosure of personal data.

For example noted in Emails.json e-mail address “ Simonov_DE@gov.ru”, which belongs to a certain Simonov D.E., is PD,  because e-mail contains the surname of certain individual which makes it a subject of Federal Law No. 152-FZ "On Personal Data". 
The list that contains some e-mails from Emails.json with PD:

"laktionov@arenda1c.ru",
 "Dobrydnev.AE@parma.ru",
  "mbudko@servicetrend.ru",
 "yaginaEN@avt-1c.ru",
  "massonsergey@yandex.ru",
  "s.krechetov@irbis-group.ru",
  "s.rudakova@legionsecurity.ru",
 "vdenezhkin@bureau-amk.ru",
  "t_antropova@audit-escort.ru",
  "artem.garvikov@gmail.com",
  "tkachev_denis@bk.ru",
  "uvmaximova@a-data.pro",

<Reasons/Legal notes>

**Comment by slcls** [comment]
Currently in review, we will get back to you soon!

**Comment by slcls** [comment]
**Federal Law of 27 July 2006 N 152-FZ ON PERSONAL DATA** - makes no distinction between whether an email is personal or not. Emails are classified into two types: those for personal use (representing solely an individual) and those for commercial use (represents an organization, a business, or even a government branch). The second category is accessibility, which can be classified as Restricted (this is where "personal emails" belong, where email providers securely store them), Controlled (mostly school or work emails that belong to a specific organization such as a school or a company), and Public (This is where OUR DATA belongs, publicly accessible information... made available publicly as a contact for concerns and such).

As for "Simonov_DE@gov.ru," that email address is associated with the "Federal Protection Service" - Press and Public Relations Department. It also falls under the category of "Publicly available data," as it does not qualify as "Personal Information" under any International Guidelines for Data Classification.

![Screenshot 2022-03-23 085520](https://user-images.githubusercontent.com/80667677/159601879-ce182921-cc13-40f8-b70b-f85b9807cf0b.png)

As an example, suppose a company has one person in charge of the finance department... That person provided his "company email" so that the press and media could contact him directly. This is the same situation in which Simonov_DE@gov.ru is directly affiliated with and representing an organization, in this case... a branch of the federal government.
The same scenario also applies to other emails stated above.

We appreciate your concern!
